kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-volume-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: my-volume
  resources:
    requests:
      storage: 2Gi