kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-volume
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/my-volume"