apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:   
    matchLabels:
      app: web-app
  template:
    metadata:
      name: web-app-pod
      labels:
        app: web-app
    spec:
      containers:
        - name: website
          image: kriztoffa/website:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000


